---
title: "Balance Communication Project"
author: "Levi_Bagwell"
date: "April 16, 2020"
output: html_document

Goals: Create a code using python that will communicate with a balance, take readings at certain time intervals, and also put those readings into a .csv file.

Part 1: Levi - Establish communication with balance. 

#!/usr/bin/env python3
import time
import serial
import csv

def conscale():
	ser=serial.Serial(
		port='/dev/ttyUSB0',
		baudrate=9600,
		parity='N',
		stopbits=1,
		bytesize=serial.SEVENBITS,
		timeout=None,
		xonxoff=True,
		rtscts=False,
		dsrdtr=False);
	x=ser.readline()
	return x

The code above was designed to communicate and take readings from the balance. During the development and trouble shooting of the code we decided that it would be much easier to interface through a raspberry pi and so that is what we used to design the code. The first part of this project was determining the port that the raspberry pi was using to communicate through the balance. It was determined that the port was '/dev/ttyUSB0',. After determining port I was able to call the port and look at all of communication pieces that the balance was sending to the raspberry pi. These pieces include baudrate, parity, stopbits, bytesize, timeout, XONXOFF which is the handshake between the pi and the scale, this has to be "true" for the scale to send the data it is reading to the pi. After determining the communication pieces I had to mirror those pieces with my code in the ser=serial.Serial port creation to get proper communication with the balance. After the communication pieces had been added to the code I used While 1 print x to determine that i had established a way to get the data from the balance. This code printed every single mass reading into the python block. The ser.readline() function will then read the lines from the ser port created above. Then that value is returned so that it can be called using the conscale function

Resources Consulted: 
- Balance Communication (instructables.com)
- Software Interfaces Sartorius Balances to PC(windmill.co.uk)
- Balance Communication Software WinCT (Balances.com)
 

Part 2: Gus - Design code to take readings at certain time intervals
#For the function i am contributing to, i am looking into possible software that will allow the scale to take readings at certain time intervals. I have been specifically looking into RsWeight programs to help with the issue. In the program, one can set many perameters and take readings at specific intervals. There is options in this program to export to an Excell file and have the data arranged respectively. Need to see what components are required for the specific program and if its a possibility.
I believe the code below will take readings every 10 seconds by continuously exucuting Levis code.
I need to figure out a stop code so it will not take measurments continuously


import time

def readmass():
    LEVIS CODE IS INSERTED HERE I BELIEVE
    time.sleep(10)

while True:
    readmass()
    
Some redactions... this is edited code that has a "stop time" 
Emily needs to add csv file code

def readmass():
	t_end = time.time() + 15;
	emily needs to make csv file to report to
		while time.time() < t_end:
			'python writes to csv'
			time.sleep(3)
		
    
Resources Consulted:
- Software info (https://www.aandd.jp/products/software/winct.html)
- Python guide https://docs.python.org/3.4/library/time.html

Part 3: Emily - Design code to insert readings into certain parts of a .csv file.
After the readings are collected at specific time intervals and recorded, they will need to be placed in an orderly fasion in a program. 
Excel will not be used, but rather a csv file. A csv file is is a delimited text file that uses a comma to separate values. 
A CSV file is different than a XLS file because a CSV format is a plain text format in which values are seperated by commas. An XLS file format is an Excel sheets binary file format that hold information about all the worksheets in a file, both content and formatting. 
Code will be created in order to place the recordings in certain cells in the .csv file. The recordings will be labeled accordingly using a code. 
This is the last step in the project, so research is continuing on the best way to format the data in the .csv file, while we establish communication with the scale. 
This is just a start there may need to be more added.

Import CSV
Result = ()
with open('output.csv', 'w') as csvfile:
    csvwriter = csv.writer(csvfile)
    for row in result.items():
        csvwriter.writerow(row)
	
A few final edits:
After the code that communicated with the balance was created and successfully ran and after the code for taking readings at certain times was created and successfully ran a code was written for placing the data in a csv file. Below is the final edited code that was created and successfully ran. 
Levi and Gus's code is included in the final code below so that the code successfully runs and places the readings in the csv file. 

def readmass():
	t_end = time.time() + 15;
	with open('mass.csv', 'w', newline='') as f:
		csvwriter = csv.writer(f, delimiter = ',',quotechar='|', quoting=csv.QUOTE_MINIMAL )
		while time.time() < t_end:
			csvwriter.writerow([conscale()])
			time.sleep(3)

Resources Consulted:
CSV file management: https://www.geeksforgeeks.org/csv-file-management-using-c/
What is a CSV File and How to open the CSV File Format: https://www.freecodecamp.org/news/what-is-a-csv-file-and-how-to-open-the-csv-file-format/


THE FINAL CODE

import time
import serial
import csv

def conscale():
	ser=serial.Serial(
		port='/dev/ttyUSB0',
		baudrate = 9600,
		parity=serial.PARITY_EVEN,
		stopbits=1,
		bytesize=serial.SEVENBITS,
		timeout=None,
		xonxoff=True,
		rtscts=False,
		dsrdtr=False);	
	x=ser.readline()
	return x
	

def readmass():
	t_end = time.time() + 15;
	with open('mass.csv', 'w', newline='') as f:
		csvwriter = csv.writer(f, delimiter = ',',quotechar='|', quoting=csv.QUOTE_MINIMAL )
		while time.time() < t_end:
			csvwriter.writerow([conscale()])
			time.sleep(3)
			
	
 readmass()
